use test

create table dbo.query
(
    id int identity(1,1) primary key,
    query nvarchar(max) not null,
    created_at datetime not null default getdate()
)
go

CREATE TABLE Widget
(
    WidgetID int identity(1,1) not null,
    WidgetName varchar(100) not null,
    WidgetDesc varchar(200) not null
)
INSERT INTO Widget VALUES
('thingamajig','A jig you cannot remember'),
('doodad','A hair style you cannot remember'),
('whatchamacallit', 'A thing for which you cannot remember');
SELECT * FROM Widget;;
go

-- Create table to add the clustered index
CREATE TABLE Production.TransactionHistoryArchive1
   (
      CustomerID uniqueidentifier DEFAULT NEWSEQUENTIALID()
      , TransactionID int IDENTITY (1,1) NOT NULL
      , CONSTRAINT PK_TransactionHistoryArchive1_CustomerID PRIMARY KEY NONCLUSTERED (CustomerID)
   )
;

-- Now add the clustered index
-- CREATE CLUSTERED INDEX CIX_TransactionID ON Production.TransactionHistoryArchive1 (TransactionID);

CREATE TABLE dbo.PurchaseOrderDetail (
    PurchaseOrderID INT NOT NULL,
    LineNumber SMALLINT NOT NULL,
    ProductID INT NULL,
    UnitPrice MONEY NULL,
    OrderQty SMALLINT NULL,
    ReceivedQty FLOAT NULL,
    RejectedQty FLOAT NULL,
    DueDate DATETIME NULL
);
go

-- how to create GUID autogenerated not modifiable
-- how to create a primary Key
-- how to create a default Value
-- What is identity in mssql: it is a column that is autoincremented

-- how to prevent modification of a Column:
--
-- to autoincrement with int: identity(1,1)

CREATE TABLE dbo.PurchaseOrderDetail2 (
  -- how to create a primary key mssql
    Id uniqueidentifier NOT NULL default newid() primary key UNIQUE?,
  -- create primary key on two Columns

    LineNumber SMALLINT NOT NULL,
    ProductID INT NULL,
    UnitPrice MONEY NULL,
    OrderQty SMALLINT NULL,
    ReceivedQty FLOAT NULL,
    RejectedQty FLOAT NULL,
    DueDate DATETIME NULL,
-- how to create an index mssql
    CONSTRAINT IX_PurchaseOrderDetail2_ProductID UNIQUE (ProductID)
-- how to create a foreign key mssql
    CONSTRAINT FK_PurchaseOrderDetail2_ProductID FOREIGN KEY (ProductID)
  -- how to reference a table
  -- it means that the column ProductID in this table is a foreign key that references the column ProductID in the table PurchaseOrderDetail
    REFERENCES dbo.PurchaseOrderDetail(ProductID)
  -- how to delete a row when the reference is deleted
    ON DELETE CASCADE
  -- how to update a row when the reference is updated
    ON UPDATE CASCADE
  -- how to create index for two columns mssql
    CONSTRAINT IX_PurchaseOrderDetail2_ProductID_UnitPrice UNIQUE (ProductID, UnitPrice)
);
go

-- i can create functions, procedures, triggers, views, loops, ifs, etc inside the engine and it gets compiled
